import {
  Home,
  Box,
  DollarSign,
  UserPlus,
  Users,
  Gift,
  Chrome,
  Settings,
  FolderPlus,
  File,
  Command,
  Star,
  Cloud,
  Book,
  FileText,
  Server,
  Image,
  Sliders,
  Map,
  GitPullRequest,
  Calendar,
  Edit,
  Mail,
  MessageSquare,
  UserCheck,
  Layers,
  HelpCircle,
  Database,
  Headphones,
  Mic,
  ShoppingBag,
  Search,
  AlertOctagon,
  Lock,
  Briefcase,
  BarChart,
  Target,
  List,
  Package,
  Truck,
} from "react-feather";

export const MENUITEMS = [
  {
    title: "Dashboard",
    icon: Home,
    type: "sub",
    badgeType: "primary",
    active: false,
    children: [
      {
        path: "/admindashboard/dashboard",
        title: "Dashboard",
        type: "link",
      },
    ],
  },
  {
    title: "Vendors",
    icon: Truck,
    type: "sub",
    active: false,
    children: [
      { path: "/vendor/viewvendors", title: "View Vendors", type: "link" },
    ],
  },
  {
    title: "Products",
    icon: Package,
    type: "sub",
    active: false,
    children: [
      { path: "/product/viewproducts", title: "View Products", type: "link" },
    ],
  },
  {
    title: "Users",
    icon: Users,
    type: "sub",
    active: false,
    children: [{ path: "/user/viewusers", title: "View Users", type: "link" }],
  },
  {
    title: "Orders",
    icon: ShoppingBag,
    type: "sub",
    active: false,
    children: [
      { path: "/order/vieworders", title: "View Orders", type: "link" },
    ],
  },
  {
    title: "Popular",
    icon: Star,
    type: "sub",
    active: false,
    children: [
      { path: "/popular/addpopular", title: "Add Popular", type: "link" },
      { path: "/popular/popularselect", title: "View Popular", type: "link" },
    ],
  },
  {
    title: "Coupons",
    icon: Gift,
    type: "sub",
    active: false,
    children: [
      { path: "/coupons/addcoupon", title: "Add Coupon", type: "link" },
      { path: "/coupons/viewcoupons", title: "View Coupons", type: "link" },
    ],
  },
];
